### ISSUE TITLE
Crash on quantile() of merged TDigest after compress()

### ISSUE THREAD

**Issue by JulianEberius** [derrickburns/tdigest#1]
The following test case reproduces the problem:

```
TEST_F(TDigestTest, CrashAfterMerge) {
  tdigest::TDigest digest(1000);
  std::uniform_real_distribution<> reals(0.0, 1.0);
  std::random_device gen;
  for (int i = 0; i < 100000; i++) {
    digest.add(reals(gen));
  }
  digest.compress();

  tdigest::TDigest digest2(1000);
  digest2.merge(&digest);
  digest2.quantile(0.5);
}
```

From my debugging, it seems the crash happens in line 338, because the cumulative_ structure is empty after the merge. Adding a call to updateCumulative() at the end of merge() fixes the crash. 

Some background: I was using your implementation in a distributed setting, were partial results are serialized, and sent to a central node, where they are deserialized and merged into one result. The above test case simulates this and also triggers the crash (so the serialization is not the problem). Maybe the call to compress() is just wrong, but it instinctively seemed correct to compress before serialization ;-)

**Comment by derrickburns** [comment]
You are correct. Bug is fixed.

**Comment by derrickburns** [comment]
Bug is fixed. :)

Derrick
